// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxzHq6EKa-HzWqE0t0fcstp3NbyAtlA4I',
    appId: '1:537664351848:web:7a5fb374741eda2d7055dd',
    messagingSenderId: '537664351848',
    projectId: 'dartpr-a696c',
    authDomain: 'dartpr-a696c.firebaseapp.com',
    storageBucket: 'dartpr-a696c.appspot.com',
    measurementId: 'G-2E3RNGXPGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ0MfQc-mXfZFnrO2_hURXcA9kAVXphLQ',
    appId: '1:537664351848:android:f0ca8cb83e3f70d67055dd',
    messagingSenderId: '537664351848',
    projectId: 'dartpr-a696c',
    storageBucket: 'dartpr-a696c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfF2lR2eAlY-LIoJmPlpJeikTu49CwadI',
    appId: '1:537664351848:ios:32582b991c1d23e97055dd',
    messagingSenderId: '537664351848',
    projectId: 'dartpr-a696c',
    storageBucket: 'dartpr-a696c.appspot.com',
    iosClientId: '537664351848-7l4if3v8li3k19a0eg208elpe310getd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfF2lR2eAlY-LIoJmPlpJeikTu49CwadI',
    appId: '1:537664351848:ios:32582b991c1d23e97055dd',
    messagingSenderId: '537664351848',
    projectId: 'dartpr-a696c',
    storageBucket: 'dartpr-a696c.appspot.com',
    iosClientId: '537664351848-7l4if3v8li3k19a0eg208elpe310getd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication9',
  );
}
